export {default as CalenderIcon} from './calendar.svg'
export {default as SearchIcon} from './searchIcon.svg'
export {default as HeaderSerachIcon} from '../icons/HeaderSerachIcon.svg'
export {default as CrossIcon} from '../icons/CrossIcon.svg'
export {default as EmiratesLogo} from '../icons/emirates_logo.svg'
export {default as LufthansaLogo} from '../icons/lufthansa_logo.svg'
export{default as GreenCheck} from '../icons/green-check.svg'